import { expect, test } from '@playwright/test'

test('analysis columns use the card height and keep selection controls outside the scroll area', async ({ page }, info) => {
  if (info.project.name === 'chromium') await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Variable scrolling')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  const columns = Array.from({ length: 60 }, (_, i) => `measurement_${i + 1}`)
  columns[0] = 'security_vulnerabilities_introduced_per_thousand_lines_of_code'
  const csv = ['date,' + columns.join(','), '2026-01-01,' + columns.map(() => '1').join(',')].join('\n')
  await page.locator('input[type=file]').setInputFiles({ name: 'wide.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: 'Inspect data', exact: true }).click()
  await page.getByRole('radio', { name: /^Regular time series/ }).check()
  const card = page.locator('section[aria-labelledby="variables-title"]')
  const list = page.getByTestId('analysis-columns-list')
  await expect(list).toHaveCSS('scrollbar-width', 'thin')
  const tableScrollbar = await page.locator('.figure-strip.panel-scroll').first().evaluate(element => getComputedStyle(element).scrollbarColor)
  await expect(list).toHaveCSS('scrollbar-color', tableScrollbar)
  await expect(list).toHaveCSS('overflow-y', 'auto')
  expect(await list.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await card.scrollIntoViewIfNeeded()
  const dimensions = await card.evaluate(element => {
    const list = element.querySelector('[data-testid="analysis-columns-list"]')!
    const rect = element.getBoundingClientRect()
    const content = list.getBoundingClientRect()
    return { height: content.height, unused: rect.bottom - content.bottom, padding: parseFloat(getComputedStyle(element).paddingBottom), scrollHeight: list.scrollHeight, clientHeight: list.clientHeight }
  })
  expect(dimensions.scrollHeight).toBeGreaterThan(dimensions.clientHeight)
  expect(dimensions.unused - dimensions.padding).toBeLessThan(2)
  if (info.project.name === 'chromium') expect(dimensions.height).toBeGreaterThan(160)
  else expect(dimensions.height).toBeLessThanOrEqual(256)
  const heading = card.getByRole('heading', { name: 'Select analysis columns' })
  const headingBefore = await heading.boundingBox()
  await list.evaluate(element => { element.scrollTop = element.scrollHeight })
  await expect.poll(() => list.evaluate(element => element.scrollHeight - element.clientHeight - element.scrollTop)).toBeLessThan(2)
  expect(await heading.boundingBox()).toEqual(headingBefore)
  const last = list.getByRole('checkbox', { name: 'measurement_60', exact: true })
  await last.check()
  await expect(last).toBeChecked()
  await card.getByRole('button', { name: 'Clear selected columns', exact: true }).click()
  await expect(last).not.toBeChecked()
  await card.getByRole('button', { name: 'Select all columns', exact: true }).click()
  await expect(list.locator('input:checked')).toHaveCount(60)
  await card.screenshot({ path: info.outputPath('variable-list.png') })
  await page.getByRole('radio', { name: /^Independent observations/ }).check()
  await expect.poll(() => list.evaluate(element => element.clientHeight)).toBeGreaterThanOrEqual(160)
  await expect(list.getByRole('checkbox')).toHaveCount(60)
})
