import { expect, test } from '@playwright/test'

test('preview column clicks update the existing bottom chart', async ({ page }, info) => {
  test.skip(info.project.name === 'mobile-chromium', 'The mobile sheet overlays the preview; lifecycle coverage runs separately on mobile.')
  test.setTimeout(90_000)
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Stable column preview')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await page.locator('input[type=file]').setInputFiles({ name: 'columns.csv', mimeType: 'text/csv', buffer: Buffer.from('Alpha,Beta,Category\n1,10,a\n2,20,b\n3,30,a\n') })
  await page.getByRole('button', { name: 'Inspect data', exact: true }).click()
  const preview = page.getByLabel('Preview', { exact: true })
  await expect(preview.locator('tbody td').filter({ hasText: /^10$/ })).toBeVisible()
  await expect(preview.locator('tbody td').filter({ hasText: /^10$/ })).toHaveCSS('font-size', /^13\.33/)
  await expect(page.getByLabel('Physical schema').getByRole('button', { name: 'Beta', exact: true })).toHaveCSS('font-size', /^13\.33/)
  const chart = page.getByTestId('column-series')
  await expect(chart.locator('svg')).toBeVisible({ timeout: 30_000 })
  const original = await chart.elementHandle()
  const svg = await chart.locator('svg').elementHandle()
  const histogram = page.getByTestId('column-histogram')
  await expect(histogram.locator('svg')).toBeVisible()
  const originalHistogram = await histogram.elementHandle()
  const histogramSvg = await histogram.locator('svg').elementHandle()
  for (const name of ['Beta', 'Alpha', 'Beta']) {
    await page.getByLabel('Preview', { exact: true }).getByRole('button', { name, exact: true }).click()
    await expect(chart).toHaveAttribute('aria-label', `${name} in row order`)
    expect(await original!.evaluate(node => node === document.querySelector('[data-testid="column-series"]'))).toBe(true)
    expect(await svg!.evaluate(node => node === document.querySelector('[data-testid="column-series"] svg'))).toBe(true)
    await expect(histogram).toHaveAttribute('aria-label', `Histogram of ${name}`)
    expect(await originalHistogram!.evaluate(node => node === document.querySelector('[data-testid="column-histogram"]'))).toBe(true)
    expect(await histogramSvg!.evaluate(node => node === document.querySelector('[data-testid="column-histogram"] svg'))).toBe(true)
    await expect(page.locator(`dl[aria-label="Summary of ${name}"]`)).toContainText(name === 'Beta' ? '20' : '2')
  }
  await page.screenshot({ path: info.outputPath('preview-columns.png'), fullPage: true })
})

test('series retains its chart through loading, stale replies and cached switches', async ({ page }) => {
  await page.goto('/app')
  await page.evaluate(async () => {
    const { React, createRoot } = await import(new URL('/tests/support/reactRuntime.ts', location.href).href)
    const { ColumnSeriesPane } = await import(new URL('/src/components/data/ColumnSeriesPane.tsx', location.href).href)
    const host = document.createElement('div')
    host.style.cssText = 'position:fixed;inset:0;background:var(--color-panel);z-index:9999'
    document.body.append(host)
    const root = createRoot(host)
    const columns = ['Alpha', 'Beta', 'Category'].map(name => ({ id: name, name, duckdbType: name === 'Category' ? 'VARCHAR' : 'DOUBLE', nullable: false, nullCount: 0 }))
    const ready = columns.map((column, i) => ({ kind: 'ready', column: column.id, profile: {}, series: i === 2 ? null : { column: column.id, values: new Float64Array(i === 0 ? [1, 2, 3] : [10, 20, 30]), missingCells: 0 } }))
    Object.assign(window, { renderSeries: (selected: number, status: string, reply = selected, key = 'first') => root.render(React.createElement(ColumnSeriesPane, {
      key, column: columns[selected], stepLabel: 'row', description: status === 'ready' ? ready[reply] : { kind: status, column: columns[reply].id },
    })) })
  })
  const render = (selected: number, status: string, reply = selected, key = 'first') => page.evaluate(({ selected, status, reply, key }) => {
    (window as unknown as { renderSeries: (a: number, b: string, c: number, d: string) => void }).renderSeries(selected, status, reply, key)
  }, { selected, status, reply, key })
  await render(0, 'ready')
  const chart = page.getByTestId('column-series')
  await expect(chart.locator('svg')).toBeVisible()
  const original = await chart.elementHandle()
  const svg = await chart.locator('svg').elementHandle()
  const bounds = await chart.boundingBox()
  for (const [selected, status, reply, shown] of [[1, 'ready', 0, 'Alpha'], [1, 'loading', 1, 'Alpha'], [1, 'ready', 0, 'Alpha'], [1, 'ready', 1, 'Beta'], [0, 'ready', 1, 'Beta'], [0, 'ready', 0, 'Alpha']] as const) {
    await render(selected, status, reply)
    await expect(chart).toBeVisible()
    expect(await original!.evaluate(node => node === document.querySelector('[data-testid="column-series"]'))).toBe(true)
    expect(await svg!.evaluate(node => node === document.querySelector('[data-testid="column-series"] svg'))).toBe(true)
    expect(await chart.boundingBox()).toEqual(bounds)
    await expect(chart).toHaveAttribute('aria-label', `${shown} in row order`)
  }
  await page.screenshot({ path: test.info().outputPath('stable-series.png') })
  await render(2, 'ready')
  await expect(page.getByText('Category is not numeric', { exact: false })).toBeVisible()
  await expect(chart).toHaveCount(0)
  await render(1, 'failed')
  await expect(page.getByText('The column could not be profiled', { exact: false })).toBeVisible()
  await render(1, 'loading', 1, 'new-source')
  await expect(chart).toHaveCount(0)
  await render(1, 'ready', 1, 'new-source')
  await expect(chart).toHaveAttribute('aria-label', 'Beta in row order')
  await expect(page.getByRole('definition').filter({ hasText: '20' })).toBeVisible()
})
