import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {choose} from './examples/support'
const fixture=JSON.parse(readFileSync('crates/causal-core/oracle/fixtures/conditional_gaussian_bnlearn.json','utf8'))

for(const count of [30,100])test(`Gaussian inspector remains usable with ${count} variables`,async({page},info)=>{
  test.setTimeout(120_000)
  const names=Array.from({length:count},(_,i)=>`Measurement ${String(i+1).padStart(3,'0')} with a long descriptive name [units]`)
  const outcome=names[count-1]
  const csv=[names.join(','),...Array.from({length:40},(_,r)=>names.map((_,c)=>(r+1)*(c+1)+Math.sin(r+c)).join(','))].join('\n')
  await page.goto('/app')
  await page.getByRole('textbox',{name:'Project name'}).fill(`Gaussian ${count} variables`)
  await page.getByRole('button',{name:'Create project',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles({name:'many.csv',mimeType:'text/csv',buffer:Buffer.from(csv)})
  await page.getByRole('button',{name:'Inspect data',exact:true}).click()
  await page.getByRole('radio',{name:/Independent observations/}).check()
  await page.getByRole('button',{name:'Select all columns',exact:true}).click()
  await page.getByRole('button',{name:/Create prepared/}).click()
  await page.getByRole('button',{name:/Build a DAG/}).click()
  await page.getByRole('button',{name:/Substantive knowledge/}).click()
  await page.getByLabel('DAG name').fill('Many measured variables')
  await page.getByRole('button',{name:/Create DAG/}).click()
  await page.getByRole('button',{name:'From text',exact:true}).click()
  await page.getByRole('textbox',{name:'Graph text'}).fill(`dag { ${names.map(n=>`"${n}";`).join(' ')} ${names.slice(0,12).map(n=>`"${n}" -> "${outcome}";`).join(' ')} }`)
  await page.getByRole('button',{name:'Convert to DAG',exact:true}).click()
  const inspector=page.getByRole('button',{name:'Inspector',exact:true})
  if(await inspector.isVisible())await inspector.click()
  await page.getByRole('radio',{name:'Intervene',exact:true}).check()
  await page.getByRole('radio',{name:'Distribution',exact:true}).check()
  await page.getByRole('radio',{name:'Conditional Gaussian',exact:true}).check()
  const types=page.getByRole('group',{name:'Variable types',exact:true})
  await expect(types.getByRole('combobox')).toHaveCount(count)
  expect(await types.evaluate(el=>el.scrollHeight>el.clientHeight)).toBe(true)
  expect(await types.evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('searchbox',{name:'Find variable types',exact:true}).fill(`Measurement ${String(count).padStart(3,'0')}`)
  await expect(types.getByRole('combobox')).toHaveCount(1)
  await page.getByRole('searchbox',{name:'Find variable types',exact:true}).press('Escape')
  await expect(types.getByRole('combobox')).toHaveCount(count)
  await types.scrollIntoViewIfNeeded()
  await page.screenshot({path:info.outputPath(`gaussian-${count}-types.png`)})
  await page.getByRole('button',{name:'Confirm variable types',exact:true}).click()
  await page.getByRole('searchbox',{name:'Find Gaussian outcome',exact:true}).fill(`Measurement ${String(count).padStart(3,'0')}`)
  await choose(page,'Gaussian outcome',outcome)
  const parents=page.getByRole('group',{name:'Gaussian parent inputs',exact:true})
  await expect(parents.getByRole('spinbutton')).toHaveCount(12)
  expect(await parents.evaluate(el=>el.scrollHeight>el.clientHeight)).toBe(true)
  await page.getByRole('searchbox',{name:'Find parent values',exact:true}).fill('Measurement 012')
  await expect(parents.getByRole('spinbutton')).toHaveCount(1)
  await parents.getByRole('spinbutton').fill('24')
  await expect(page.getByText('1 of 12 entered',{exact:true})).toBeVisible()
  await expect(page.getByText('11 parent values are still required.',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Evaluate Gaussian query',exact:true})).toBeDisabled()
  const role=page.getByRole('radiogroup',{name:`${names[11]} Gaussian role`,exact:true})
  await role.getByRole('radio',{name:'Observe',exact:true}).focus()
  await page.keyboard.press('ArrowRight')
  await expect(role.getByRole('radio',{name:'Intervene',exact:true})).toBeChecked()
  await page.getByRole('searchbox',{name:'Find parent values',exact:true}).fill('no such variable')
  await expect(page.getByText('No parents match your search.',{exact:false})).toBeVisible()
  await page.getByRole('searchbox',{name:'Find parent values',exact:true}).press('Escape')
  await expect(parents.getByRole('spinbutton')).toHaveCount(12)
  expect(await parents.evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('searchbox',{name:'Find parent values',exact:true}).scrollIntoViewIfNeeded()
  await page.screenshot({path:info.outputPath(`gaussian-${count}-parents.png`)})
  if(info.project.name==='chromium'){
    const seam=page.getByRole('separator',{name:'Resize Inspector',exact:true})
    const box=await seam.boundingBox()
    if(box===null)throw Error('Inspector resize handle is missing')
    await page.mouse.move(box.x+box.width/2,box.y+box.height/2)
    await page.mouse.down();await page.mouse.move(box.x-220,box.y+box.height/2,{steps:10});await page.mouse.up()
    await expect(parents.getByRole('spinbutton')).toHaveCount(12)
    expect(await parents.evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({path:info.outputPath(`gaussian-${count}-wide.png`)})
  }else{
    await page.getByRole('searchbox',{name:'Find parent values',exact:true}).press('Escape')
    await expect(page.getByRole('dialog',{name:'Inspector',exact:true})).toHaveCount(0)
  }
})

test('Gaussian formula keeps symbols stable and column names out of TeX',async({page})=>{
  await page.goto('/app')
  const formulas=await page.evaluate(async()=>{
    const {conditionalGaussianQueryFormula}=await import(new URL('/src/domain/conditionalGaussianQuery.ts',location.href).href)
    const q={rows:10,columns:3,names:['Failure_%','Air {K}','Outcome \\command'],edges:[[0,2],[1,2]],variables:['discrete','continuous','continuous'],outcome:2,observations:[{variable:0,value:0},{variable:1,value:296}],interventions:[]}
    return [conditionalGaussianQueryFormula(q),conditionalGaussianQueryFormula({...q,observations:[{variable:0,value:0}],interventions:[{variable:1,value:296}]}),conditionalGaussianQueryFormula({...q,observations:[{variable:0,value:0},{variable:1,value:1e-8}]})]
  })
  expect(formulas[0].variables).toEqual(formulas[1].variables)
  expect(formulas[1].tex).toBe('p(Y\\mid \\operatorname{do}(X_{2}=296),\\allowbreak X_{1}=0)')
  expect(formulas[1].tex).not.toContain('command')
  expect(formulas[2].tex).toContain('1\\times 10^{-8}')
})

test('conditional Gaussian worker matches pinned local fits and rejects unsupported evidence',async({page})=>{
  await page.goto('/app')
  const errors=await page.evaluate(async f=>{
    const {runConditionalGaussianQuery}=await import(new URL('/src/analysis/client.ts',location.href).href)
    const errors:number[]=[]
    for(const c of f.cases){
      for(const q of c.queries){
        const request={rows:c.rows,columns:c.names.length,names:c.names,edges:c.edges,variables:c.kinds,outcome:q.outcome,observations:q.observations.map(([variable,value]:number[])=>({variable,value})),interventions:q.interventions.map(([variable,value]:number[])=>({variable,value}))}
        const result=await runConditionalGaussianQuery(new Float64Array(c.values),request)
        if(!result.ok)throw Error(JSON.stringify(result.error))
        errors.push(Math.abs(result.value.mean-q.mean),Math.abs(result.value.std-q.std))
      }
    }
    const c=f.cases[0]
    const invalid=await runConditionalGaussianQuery(new Float64Array(c.values),{rows:c.rows,columns:c.names.length,names:c.names,edges:c.edges,variables:c.kinds,outcome:2,observations:[],interventions:[]})
    if(invalid.ok)throw Error('Missing parent evidence was silently substituted')
    return errors
  },fixture)
  expect(errors).toHaveLength(24)
  expect(Math.max(...errors)).toBeLessThan(1e-9)
})

test('maintenance conditional Gaussian observations and interventions render and reopen',async({page},info)=>{
  test.setTimeout(120_000)
  await page.addInitScript(()=>localStorage.setItem('hirmos-theme','system'))
  await page.emulateMedia({colorScheme:'light',reducedMotion:'reduce'})
  const c=fixture.cases.find((c:{name:string})=>c.name==='maintenance-local')
  const rows=Array.from({length:c.rows},(_,i)=>c.names.map((_:string,j:number)=>c.values[j*c.rows+i]).join(','))
  const csv={name:'maintenance-gaussian.csv',mimeType:'text/csv',buffer:Buffer.from([c.names.join(','),...rows].join('\n'))}
  await page.goto('/app')
  await page.getByRole('textbox',{name:'Project name'}).fill('Maintenance Gaussian queries')
  await page.getByRole('button',{name:'Create project',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles(csv)
  await page.getByRole('button',{name:'Inspect data',exact:true}).click()
  await page.getByRole('radio',{name:/Independent observations/}).check()
  await page.getByRole('button',{name:'Select all columns',exact:true}).click()
  await page.getByRole('button',{name:/Create prepared/}).click()
  await page.getByRole('button',{name:/Build a DAG/}).click()
  await page.getByRole('button',{name:/Substantive knowledge/}).click()
  await page.getByLabel('DAG name').fill('Maintenance local Gaussian model')
  await page.getByRole('button',{name:/Create DAG/}).click()
  await page.getByRole('button',{name:'From text',exact:true}).click()
  await page.getByRole('textbox',{name:'Graph text'}).fill('dag { "Machine failure" -> "Process temperature [K]"; "Air temperature [K]" -> "Process temperature [K]"; }')
  await page.getByRole('button',{name:'Convert to DAG',exact:true}).click()
  const inspector=page.getByRole('button',{name:'Inspector',exact:true})
  if(await inspector.isVisible())await inspector.click()
  await page.getByRole('radio',{name:'Intervene',exact:true}).check()
  await page.getByRole('radio',{name:'Distribution',exact:true}).check()
  await page.getByRole('radio',{name:'Conditional Gaussian',exact:true}).check()
  await choose(page,'Machine failure variable type','Discrete')
  await page.getByRole('button',{name:'Confirm variable types',exact:true}).click()
  await choose(page,'Gaussian outcome','Process temperature [K]')
  await expect(page.getByRole('button',{name:'Evaluate Gaussian query',exact:true})).toBeDisabled()
  await expect(page.getByRole('spinbutton',{name:'Air temperature [K] Gaussian value',exact:true})).toHaveValue('')
  await choose(page,'Machine failure Gaussian value','0')
  await page.getByRole('spinbutton',{name:'Air temperature [K] Gaussian value',exact:true}).fill('300')
  await page.getByRole('button',{name:'Evaluate Gaussian query',exact:true}).click()
  const records=page.getByRole('list',{name:'Gaussian queries'}).locator(':scope > li')
  await expect(records).toHaveCount(1)
  await expect(records.first()).toContainText('310.012618')
  await expect(records.first()).toContainText('0.712043')
  await page.getByRole('radiogroup',{name:'Air temperature [K] Gaussian role',exact:true}).getByRole('radio',{name:'Intervene',exact:true}).check()
  await page.getByRole('spinbutton',{name:'Air temperature [K] Gaussian value',exact:true}).fill('296')
  await page.getByRole('button',{name:'Evaluate Gaussian query',exact:true}).click()
  await expect(records).toHaveCount(2)
  await expect(records.first()).toContainText('307.390004')
  await expect(records.first().getByLabel('Process temperature [K] given do(Air temperature [K] = 296), Machine failure = 0',{exact:true})).toBeVisible()
  await expect(records.first().locator('.katex-error')).toHaveCount(0)
  await expect(records.first().getByRole('definition').first()).toHaveText('Process temperature [K]')
  await records.first().scrollIntoViewIfNeeded()
  await page.screenshot({path:info.outputPath('conditional-gaussian.png')})
  const chart=records.first().locator('[_echarts_instance_]')
  const instance=await chart.getAttribute('_echarts_instance_')
  for(const theme of ['light','dark'] as const){
    await page.emulateMedia({colorScheme:theme})
    await expect(page.locator('html')).toHaveAttribute('data-theme',theme)
    await expect.poll(()=>chart.evaluate(async el=>{
      const charts=await import(new URL('/tests/support/echartsRuntime.ts',location.href).href)
      const themes=await import(new URL('/src/charts/theme.ts',location.href).href)
      const expected=themes.readChartTheme(),option=charts.getInstanceByDom(el).getOption()
      return option.xAxis[0].axisLabel.color===expected.faint&&option.tooltip[0].backgroundColor===expected.panel
    })).toBe(true)
    const audit=await chart.evaluate(async el=>{
      const charts=await import(new URL('/tests/support/echartsRuntime.ts',location.href).href)
      const themes=await import(new URL('/src/charts/theme.ts',location.href).href)
      const expected=themes.readChartTheme(),option=charts.getInstanceByDom(el).getOption()
      const luminance=(hex:string)=>{const values=hex.replace('#','').match(/../g)!.map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return values[0]*.2126+values[1]*.7152+values[2]*.0722}
      const ratio=(a:string,b:string)=>{const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
      return {series:option.series[0].lineStyle.color,palette:expected.categorical[0],font:option.xAxis[0].axisLabel.fontFamily,expectedFont:expected.font,size:option.xAxis[0].axisLabel.fontSize,expectedSize:expected.labelSize,
        lineContrast:Math.min(ratio(option.series[0].lineStyle.color,expected.panel),ratio(option.series[0].lineStyle.color,expected.well)),
        textContrast:ratio(expected.faint,expected.well),tooltipContrast:ratio(option.tooltip[0].textStyle.color,option.tooltip[0].backgroundColor)}
    })
    expect(audit.series).toBe(audit.palette)
    expect(audit.font).toBe(audit.expectedFont)
    expect(audit.size).toBe(audit.expectedSize)
    expect(audit.lineContrast).toBeGreaterThanOrEqual(3)
    expect(audit.textContrast).toBeGreaterThanOrEqual(4.5)
    expect(audit.tooltipContrast).toBeGreaterThanOrEqual(4.5)
    await expect(chart).toHaveAttribute('_echarts_instance_',instance!)
    expect(await records.first().evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1)
    await chart.scrollIntoViewIfNeeded()
    await page.screenshot({path:info.outputPath(`gaussian-result-${theme}.png`)})
    await page.getByRole('group',{name:'Gaussian parent inputs',exact:true}).scrollIntoViewIfNeeded()
    await page.screenshot({path:info.outputPath(`gaussian-controls-${theme}.png`)})
  }
  await expect(page.getByText('The curves show fitted outcome distributions, not confidence intervals.',{exact:false})).toHaveCount(1)
  await expect(records.first()).not.toContainText('A causal interpretation')
  await choose(page,'Machine failure Gaussian value','Choose a category')
  await expect(page.getByRole('button',{name:'Evaluate Gaussian query',exact:true})).toBeDisabled()
  await expect(page.getByText('1 parent value is still required.',{exact:true})).toBeVisible()
  await expect(records).toHaveCount(2)
  await page.getByRole('group',{name:'Gaussian parent inputs',exact:true}).scrollIntoViewIfNeeded()
  await page.screenshot({path:info.outputPath('conditional-gaussian-controls.png')})
  await expect.poll(()=>page.evaluate(async()=>{
    const store=await import(new URL('/src/data/projectStore.ts',location.href).href)
    const head=(await store.listProjects())[0];const saved=await store.loadProject(head.id)
    if(!saved.ok)return 0
    const {parseSnapshotValue}=await import(new URL('/src/domain/persistence.ts',location.href).href)
    if(!parseSnapshotValue(saved.value).ok)throw Error('Gaussian record failed decoding')
    return saved.value.interventionQueries.length
  })).toBe(2)
  await page.goto('/app/projects')
  await page.getByRole('button',{name:'Open Maintenance Gaussian queries',exact:true}).click()
  await page.locator('input[type=file][accept*=".csv"]').setInputFiles(csv)
  const sections=page.getByRole('button',{name:'Expand section list',exact:true})
  if(await sections.isVisible())await sections.click()
  await page.getByRole('navigation',{name:'Workspace sections'}).getByRole('button',{name:/DAG workspace/}).click()
  if(info.project.name==='mobile-chromium')await inspector.click()
  await page.getByRole('radio',{name:'Intervene',exact:true}).check()
  await page.getByRole('radio',{name:'Distribution',exact:true}).check()
  await page.getByRole('radio',{name:'Conditional Gaussian',exact:true}).check()
  await expect(records).toHaveCount(2)
  await expect(records.first()).toContainText('307.390004')
})
