import { expect, test } from '@playwright/test'

test('intervention effects run from the root-cause selector and retain results on cancel', async ({ page }, info) => {
  test.skip(info.project.name !== 'chromium', 'Desktop workflow also checks the mobile result layout.')
  test.setTimeout(120_000)
  await page.routeWebSocket(/.*/, socket => socket.close())
  const csv = { name: 'root-cause-baseline.csv', mimeType: 'text/csv', buffer: Buffer.from('X,Y\n' + Array.from({ length: 200 }, (_, index) => `${index % 2},${2 * (index % 2) + (index % 7) / 10}`).join('\n')) }
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Root-cause workflow')
  await page.getByRole('button', { name: 'Create project' }).click()
  await page.locator('input[type=file]').setInputFiles(csv)
  await page.getByRole('button', { name: 'Inspect data' }).click()
  await page.getByRole('radio', { name: 'Independent observations' }).click()
  await page.getByRole('checkbox', { name: 'X', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Y', exact: true }).check()
  await page.getByRole('button', { name: 'Create prepared dataset version' }).click()
  await expect(page.getByRole('status').filter({ hasText: /^Cross-section, / })).toContainText('200 rows')
  await page.getByRole('navigation', { name: 'Workspace sections' }).getByRole('button', { name: /Causal model analysis/ }).click()
  await expect(page.getByRole('region', { name: 'Root-cause graph selection' })).toContainText('Use for causal model analysis')
  await page.screenshot({ path: info.outputPath('root-cause-selection.png'), fullPage: true })
  await page.getByRole('navigation', { name: 'Workspace sections' }).getByRole('button', { name: /DAG workspace/ }).click()
  await page.getByRole('button', { name: /^Substantive knowledge/ }).click()
  await page.getByLabel('DAG name').fill('X affects Y')
  await page.getByRole('button', { name: 'Create DAG draft' }).click()
  for (const [label, option] of [['Proposed cause', 'X'], ['Proposed effect', 'Y']]) {
    await page.getByRole('combobox', { name: label }).click()
    await page.getByRole('option', { name: option, exact: true }).click()
  }
  await page.getByRole('textbox', { name: /Rationale/ }).first().fill('Y is twice X in this verification dataset.')
  await page.getByRole('button', { name: 'Add the arrow' }).click()
  await page.getByRole('button', { name: 'Use for causal model analysis', exact: true }).click()

  await page.getByRole('radio', { name: 'Intervention effects', exact: true }).check()
  const setup = page.getByRole('region', { name: 'Intervention effects setup' })
  await setup.getByText('Sampling settings', { exact: true }).click()
  await page.getByLabel('Trees per model', { exact: true }).fill('20')
  await page.getByLabel('Simulations', { exact: true }).fill('10')
  await setup.getByRole('button', { name: 'Run analysis', exact: true }).click()
  const result = page.getByRole('region', { name: 'Intervention effect results' })
  await expect(result).toBeVisible({ timeout: 90000 })
  await expect(result).toContainText('higher Y')
  await expect(result.getByRole('table')).toContainText('All rows')
  await page.screenshot({ path: info.outputPath('effects-desktop.png'), fullPage: true })
  await page.getByLabel('Trees per model', { exact: true }).fill('1000')
  await page.getByLabel('Simulations', { exact: true }).fill('1000')
  await setup.getByRole('button', { name: 'Run analysis', exact: true }).click()
  await expect(setup.getByLabel('Causal model analysis running')).toBeVisible()
  await setup.getByRole('button', { name: 'Cancel run', exact: true }).click({ force: true })
  await expect(setup.getByRole('alert')).toContainText('The analysis was cancelled.')
  await expect(result).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await result.scrollIntoViewIfNeeded()
  await expect(result).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('effects-mobile.png'), fullPage: true })
  await expect.poll(() => page.evaluate(async () => {
    const store = await import(new URL('/src/data/projectStore.ts', location.href).href)
    const header = (await store.listProjects()).find((entry: { name: string }) => entry.name === 'Root-cause workflow')
    if (!header) return false
    const saved = await store.loadProject(header.id)
    return saved.ok && saved.value.rootCause.effects.length === 1 && saved.value.rootCause.selection !== null
  })).toBe(true)
  await page.goto('/app/projects')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Open Root-cause workflow', exact: true }).click()
  await page.getByRole('heading', { name: 'Choose the data file again' }).waitFor()
  await page.locator('input[type=file]').setInputFiles(csv)
  await page.getByRole('navigation', { name: 'Workspace sections' }).getByRole('button', { name: /Causal model analysis/ }).click()
  await page.getByRole('radio', { name: 'Intervention effects', exact: true }).check()
  await expect(result).toBeVisible()
})
