import { expect, test } from '@playwright/test'
import { chapter } from './examples/support'

test('March cohort distinguishes a valid panel from a two-period method restriction', async ({ page }, info) => {
  await page.goto('/app')
  await page.getByRole('button', {name:'Open AI adoption, March cohort',exact:true}).click()
  await chapter(page,/Estimation/)
  await page.getByRole('radio',{name:/^Interventions/}).click()
  await page.getByRole('radio',{name:/Panel difference-in-differences/}).click()
  await page.getByRole('radio',{name:'Regression',exact:true}).click()
  await expect(page.getByRole('button',{name:/^Run panel difference-in-differences/})).toBeDisabled()
  const requirements=page.getByRole('button',{name:'Study and method requirements',exact:true})
  if(await requirements.isVisible())await requirements.click()
  const summary=page.getByRole('region',{name:'Checked panel structure',exact:true})
  await expect(summary).toBeVisible({timeout:60_000})
  await expect(summary).toContainText('Treated / control units')
  await expect(summary).toContainText('3 / 3')
  await expect(summary).toContainText('Pre / post periods')
  await expect(summary).toContainText('12 / 12')
  await expect(summary).toContainText('Adoption period')
  await expect(summary).toContainText('13')
  await expect(page.getByText(/^Ready: 3 treated/)).toHaveCount(0)
  await expect(page.getByText(/This is a method restriction, not an invalid panel grid/).last()).toBeVisible()
  await expect(page.getByRole('button',{name:/^Run panel difference-in-differences/,includeHidden:true})).toBeDisabled()
  await summary.scrollIntoViewIfNeeded()
  await page.screenshot({path:info.outputPath('march-cohort-method-restriction.png')})
  await summary.screenshot({path:info.outputPath('panel-structure.png')})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
})
