import { expect, test } from '@playwright/test'

test('pipeline preview keeps its table through selection, errors and recovery', async ({ page }, info) => {
  test.skip(info.project.name !== 'chromium', 'Desktop side-by-side pane identity')
  test.setTimeout(90_000)
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Stable pipeline')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await page.getByRole('radio', { name: 'Build a pipeline' }).click({ force: true })
  await page.getByRole('button', { name: 'Open the editor' }).click()
  const harness = page.getByRole('region', { name: 'Build a pipeline', exact: true })
  await harness.getByTestId('block-input-1').click()
  await page.getByRole('button', { name: 'Remove block', exact: true }).click()
  await page.getByRole('toolbar', { name: 'Add a block' }).getByRole('button', { name: 'Script', exact: true }).click()
  const editor = harness.getByRole('textbox', { name: 'Python script', exact: true })
  await editor.fill('import pandas as pd\nprepared = pd.DataFrame({"x": [1,2,3]})')
  const node = harness.locator('[data-testid^="block-script-"]')
  await expect(node).toContainText('3 rows, 1 column', { timeout: 60_000 })
  const preview = harness.getByTestId('pipeline-preview')
  const table = preview.locator('table')
  await expect(table).toBeVisible()
  await table.evaluate(element => element.setAttribute('data-retained', 'yes'))
  const before = await preview.boundingBox()
  await node.evaluate(element => {
    element.setAttribute('data-retained', 'yes')
    const heights: number[] = []
    const observer = new ResizeObserver(() => { heights.push(element.getBoundingClientRect().height); element.setAttribute('data-heights', JSON.stringify(heights)) })
    observer.observe(element)
    setTimeout(() => observer.disconnect(), 15_000)
  })
  await editor.fill('import pandas as pd\nimport time\ntime.sleep(1)\nprepared = pd.DataFrame({"x": [1,2,3], "y": [2,4,6]})')
  await expect(table.getByRole('columnheader', { name: /^y/ })).toBeVisible()
  await expect(table).toHaveAttribute('data-retained', 'yes')
  await expect(node).toHaveAttribute('data-retained', 'yes')
  const heights: number[] = JSON.parse(await node.getAttribute('data-heights') ?? '[]')
  expect(heights.length).toBeGreaterThan(0)
  expect(Math.max(...heights) - Math.min(...heights)).toBeLessThan(0.5)
  await editor.fill('prepared = missing_dataframe')
  await expect(harness.getByTestId('block-status')).toContainText('NameError')
  await expect(harness.getByText(/NameError/)).toHaveCount(1)
  await expect(preview).toContainText('No preview available.')
  await expect(table).toHaveAttribute('data-retained', 'yes')
  await expect(table).toBeHidden()
  await editor.fill('import pandas as pd\nprepared = pd.DataFrame({"x": [1,2,3], "y": [3,6,9]})')
  await expect(table).toBeVisible({ timeout: 30_000 })
  await expect(table).toHaveAttribute('data-retained', 'yes')
  await expect(table.getByRole('cell', { name: '9', exact: true })).toBeVisible()
  const after = await preview.boundingBox()
  expect(after?.height).toBeCloseTo(before!.height, 0)
  await page.screenshot({ path: info.outputPath('pipeline-preview.png') })
})
