import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { chapter, choose, createDag, addArrow, identify } from './examples/support'

const oracle = JSON.parse(readFileSync('crates/analysis-wasm/test-data/predictor-synth-texas.json', 'utf8'))
const exact = new DataView(new Uint8Array(oracle.exact.rows).buffer)
const csv = ['unit,period,policy,' + oracle.data.columns.join(','), ...oracle.data.rows.map((row: { unit: number; period: number }, i: number) => [row.unit, row.period, row.unit === 48 && row.period >= 1994 ? 1 : 0, ...oracle.data.columns.map((_: string, j: number) => exact.getFloat64((i * oracle.data.columns.length + j) * 8, true))].join(','))].join('\n')
const source = { name: 'texas-synth.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) }
test.use({ contextOptions: { reducedMotion: 'reduce' }, actionTimeout: 30_000 })

test('Texas predictor-based synthetic control: full UI, plots, run row, oracle and restoration', async ({ page }, info) => {
  test.setTimeout(300_000)
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Texas predictor synthetic control')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await page.locator('input[type=file]').setInputFiles(source)
  await page.getByRole('button', { name: 'Inspect data', exact: true }).click()
  await page.getByRole('radio', { name: /^Panel/ }).click()
  await choose(page, 'Unit column', 'unit')
  await choose(page, 'Time column', 'period')
  await page.getByRole('button', { name: 'Select all columns', exact: true }).click()
  await page.getByRole('button', { name: /Create prepared/ }).click()
  await expect(page.getByRole('heading', { name: 'Next steps', exact: true })).toBeVisible({ timeout: 90_000 })
  await createDag(page, 'Texas intervention')
  await addArrow(page, 'policy', 'bmprison', 'The policy intervention can change the prison population. The synthetic-control comparison uses untreated states to construct the no-intervention path.')
  await identify(page, { graph: 'Texas intervention', treatment: 'policy', outcome: 'bmprison', target: /^Treated rows/, mechanism: 'Policy change', sentence: 'Texas is exposed from 1994; the donor states are untreated.' })
  await chapter(page, /Estimation/)
  await page.getByRole('radio', { name: /^Interventions/ }).click()
  await page.getByRole('radio', { name: /^Synthetic control/ }).click()
  await choose(page, 'Synthetic treated unit', '48')
  await choose(page, 'Synthetic intervention period', '1994')
  await page.getByRole('button', { name: 'Select all donor units', exact: true }).click()
  for (const name of ['poverty', 'income']) await page.getByRole('group', { name: 'Ordinary predictors', exact: true }).getByRole('checkbox', { name, exact: true }).check()
  for (const special of oracle.request.special) {
    await page.getByRole('button', { name: 'Add period-specific predictor', exact: true }).click()
    const index = oracle.request.special.indexOf(special) + 1
    await choose(page, `Period-specific predictor ${index}`, oracle.data.columns[special.column])
    const periods = page.getByRole('group', { name: `Special predictor ${index} periods`, exact: true })
    for (let year = 1985; year <= 1993; year++) await periods.getByRole('checkbox', { name: String(year), exact: true }).setChecked(special.periods.includes(year))
  }
  const run = page.getByRole('button', { name: 'Run synthetic control', exact: true })
  await expect(run).toBeEnabled({ timeout: 30_000 })
  await run.scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('configured-light.png') })
  const row = page.getByTestId('estimation-run-row')
  const before = await row.boundingBox()
  await run.click()
  await expect(page.getByRole('button', { name: 'Cancel run', exact: true })).toBeVisible()
  const during = await row.boundingBox()
  expect(during!.height).toBe(before!.height)
  const cancel = await page.getByRole('button', { name: 'Cancel run', exact: true }).boundingBox()
  const runBox = await run.boundingBox()
  expect(Math.abs(cancel!.y - runBox!.y)).toBeLessThan(5)
  const results = page.getByTestId('predictor-synthetic-results').first()
  await expect(results).toBeVisible({ timeout: 120_000 })
  await results.scrollIntoViewIfNeeded()
  await expect(results.getByText('Evaluation limit reached', { exact: true }).first()).toBeVisible()
  await expect(results.getByRole('img', { name: 'Observed and synthetic bmprison for 48', exact: true })).toBeVisible()
  await results.getByRole('img', { name: 'Observed and synthetic bmprison for 48', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('result-light.png') })
  await page.getByRole('button', { name: 'Change theme', exact: true }).click()
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark')
  await page.screenshot({ path: info.outputPath('result-dark.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await results.getByRole('img', { name: 'Observed and synthetic bmprison for 48', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('result-mobile.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1000 })
  const expand = page.getByRole('button', { name: 'Expand section list', exact: true })
  if (await expand.isVisible()) await expand.click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export project', exact: true }).click()
  const path = await (await download).path()
  const snapshot = JSON.parse(readFileSync(path!, 'utf8')).project
  const saved = snapshot.estimationRuns.at(-1)
  expect(saved.kind).toBe('predictor-synthetic-control-run')
  expect(saved.evidence.selection).toEqual({ kind: 'optimized', start: 'regression', method: 'nelder-mead', evaluations: 501, convergenceCode: 1 })
  for (const [actual, expected] of [[saved.evidence.donorWeights, oracle.fit.w], [saved.evidence.balance.map((b: { weight: number }) => b.weight), oracle.fit.v], [saved.evidence.synthetic, oracle.synthetic], [saved.evidence.gaps, oracle.gaps]]) {
    expect(actual).toHaveLength(expected.length)
    actual.forEach((value: number, i: number) => expect(Math.abs(value - expected[i])).toBeLessThanOrEqual(1e-10 * Math.max(1, Math.abs(expected[i]))))
  }
  const postGaps = oracle.gaps.filter((_: number, i: number) => oracle.request.plot_periods[i] >= 1994)
  const total = postGaps.reduce((sum: number, gap: number) => sum + gap, 0)
  expect(saved.estimate.effect.aggregate.cumulative).toBeCloseTo(total, 5)
  expect(saved.estimate.effect.aggregate.average).toBeCloseTo(total / postGaps.length, 5)
  const valid = await page.evaluate(async snapshot => {
    const persistence = await import(new URL('/src/domain/persistence.ts', location.href).href)
    const altered = structuredClone(snapshot)
    altered.estimationRuns.at(-1).configuration.interventionPeriod = 1985
    const forged = structuredClone(snapshot)
    forged.estimationRuns.at(-1).estimate.effect.aggregate.average += 1
    return { valid: persistence.parseSnapshotValue(snapshot).ok, altered: persistence.parseSnapshotValue(altered).ok, forged: persistence.parseSnapshotValue(forged).ok }
  }, snapshot)
  expect(valid).toEqual({ valid: true, altered: false, forged: false })
  await expect.poll(() => page.evaluate(async id => {
    const store = await import(new URL('/src/data/projectStore.ts', location.href).href)
    const saved = await store.loadProject(id)
    return saved.ok ? saved.value.estimationRuns.length : 0
  }, snapshot.project.id)).toBe(1)
  await page.goto('/app/projects')
  await page.getByRole('button', { name: 'Open Texas predictor synthetic control', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Choose the data file again', exact: true })).toBeVisible()
  await page.locator('input[type=file]').setInputFiles(source)
  await chapter(page, /Estimation/)
  await expect(results).toBeVisible({ timeout: 30_000 })
  await expect(page.getByRole('combobox', { name: 'Synthetic treated unit' })).toContainText('48')
  expect(errors).toEqual([])
})

test('legacy outcome-history synthetic control remains runnable and retains its uncertainty route', async ({ page }) => {
  test.setTimeout(120_000)
  await page.goto('/app')
  await page.getByRole('button', { name: 'Open Proposition 99 and cigarette sales', exact: true }).click()
  await chapter(page, /Estimation/)
  await expect(page.getByText('Mark the intervention', { exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Synthetic treated unit' })).toHaveCount(0)
  const run = page.getByRole('button', { name: 'Run synthetic control', exact: true })
  await expect(run).toBeEnabled({ timeout: 30_000 })
  await run.click()
  await expect(page.getByRole('button', { name: 'Cancel run', exact: true })).toHaveCount(0, { timeout: 60_000 })
  await expect(page.getByTestId('predictor-synthetic-results')).toHaveCount(0)
  await expect(page.getByText(/Pre-period loss/).first()).toBeVisible()
})
