import { expect, test } from '@playwright/test'
import { fileURLToPath } from 'node:url'
import { choose } from './examples/support'

const source = fileURLToPath(new URL('../docs/2026-09-17-richdata01/data/onboarded_with_incidents_2026-06-11.parquet', import.meta.url))

test('inspect the real Parquet dataset through direct upload', async ({ page }, info) => {
  test.setTimeout(180_000)
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Richdata direct upload')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await page.locator('input[type=file]').setInputFiles(source)
  await page.getByRole('button', { name: /Inspect data/ }).click()
  await expect(page.getByText('Choose the observation structure', { exact: true })).toBeVisible({ timeout: 90_000 })
  console.log('Dataset size:', await page.locator('dl[aria-label="Dataset size"]').innerText())
  console.log('Headings:', await page.getByRole('heading').allTextContents())
  console.log('Preparation buttons:', await page.getByRole('button', { name: /prepar|edit|clean/i }).allTextContents())
  console.log('Alerts:', await page.getByRole('alert').allTextContents())
  await page.getByText('Choose the observation structure', { exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('direct-upload.png') })
  await page.getByRole('radio', { name: /Independent observations/ }).check()
  console.log('After choosing structure:', await page.getByRole('button', { name: /prepar|edit|clean/i }).allTextContents())
  await page.getByRole('button', { name: 'Select all columns', exact: true }).click()
  console.log('Missing-value controls:', await page.locator('section[aria-labelledby="missingness-title"]').innerText())
  console.log('After choosing columns:', await page.getByRole('button', { name: /prepar|edit|clean/i }).allTextContents())
  await page.getByRole('radio', { name: /^Panel/ }).check()
  await choose(page, 'Unit column', 'resource_id')
  await page.getByRole('combobox', { name: 'Time column', exact: true }).click()
  console.log('Time columns:', await page.getByRole('option').allTextContents())
  await page.keyboard.press('Escape')
  await choose(page, 'Time column', 'year_week')
  console.log('Panel alerts:', await page.getByRole('alert').allTextContents())
  console.log('Panel missingness:', await page.locator('section[aria-labelledby="missingness-title"]').innerText())
  console.log('Panel action count:', await page.getByRole('button', { name: 'Create prepared dataset version' }).count())
  await page.locator('section[aria-labelledby="missingness-title"]').scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('structure-selected.png') })
})

test('reproduce weekly-key parsing and missing-data alignment through direct upload', async ({ page }, info) => {
  test.setTimeout(120_000)
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Richdata weekly upload')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await page.locator('input[type=file]').setInputFiles(fileURLToPath(new URL('../docs/2026-09-17-richdata01/data/105w_merged_weekly.parquet', import.meta.url)))
  await page.getByRole('button', { name: /Inspect data/ }).click()
  await expect(page.getByText('Choose the observation structure', { exact: true })).toBeVisible({ timeout: 90_000 })
  console.log('Dataset size:', await page.locator('dl[aria-label="Dataset size"]').innerText())
  const preview = page.locator('table').filter({ has: page.getByRole('columnheader', { name: 'year_week', exact: true }) })
  await preview.scrollIntoViewIfNeeded()
  const firstWeek = () => preview.evaluate((table) => {
    const index = Array.from(table.querySelectorAll('thead th')).findIndex((cell) => cell.getAttribute('aria-label') === 'year_week')
    return table.querySelector('tbody tr[aria-rowindex="2"]')?.children[index]?.textContent?.trim() ?? ''
  })
  await expect.poll(firstWeek).not.toMatch(/^(|…)$/)
  console.log('First weekly key shown in preview:', await firstWeek())
  await page.getByRole('radio', { name: /^Regular time series/ }).check()
  await choose(page, 'Time column', 'year_week')
  await choose(page, 'Source frequency', 'Weekly')
  await choose(page, 'Time interpretation', 'ISO week (2024-W02)')
  await page.getByRole('button', { name: 'Select all columns', exact: true }).click()
  await page.getByRole('radio', { name: 'Lag-aware sample exclusion', exact: true }).check()
  const cutoff = page.getByRole('combobox', { name: 'Sample cutoff', exact: true })
  const following = page.getByRole('checkbox', { name: 'Exclude following samples through the cutoff window.', exact: true })
  await cutoff.scrollIntoViewIfNeeded()
  console.log('Cutoff bounds:', await cutoff.boundingBox(), 'Following bounds:', await following.boundingBox())
  await page.screenshot({ path: info.outputPath('lag-exclusion-layout.png') })
  const prepare = page.getByRole('button', { name: 'Create prepared dataset version', exact: true })
  await prepare.scrollIntoViewIfNeeded()
  const before = await prepare.boundingBox()
  await prepare.evaluate((button) => button.setAttribute('data-layout-probe', 'same-button'))
  await prepare.click()
  await expect(page.getByText('year_week repeats at sorted row 3. A regular time series needs one row per time point.', { exact: true })).toBeVisible({ timeout: 30_000 })
  await expect(prepare).toHaveAttribute('data-layout-probe', 'same-button')
  await expect(prepare).toBeEnabled()
  const failed = await prepare.boundingBox()
  expect(Math.abs(failed!.x - before!.x)).toBeLessThan(1)
  expect(Math.abs(failed!.width - before!.width)).toBeLessThan(1)
  console.log('After weekly interpretation:', await page.getByRole('alert').allTextContents())
  await page.screenshot({ path: info.outputPath('weekly-key-error.png') })
  await page.getByRole('radio', { name: /^Panel/ }).check()
  await page.getByRole('combobox', { name: 'Unit column', exact: true }).click()
  console.log('Weekly panel unit choices:', await page.getByRole('option').allTextContents())
  await page.keyboard.press('Escape')
  console.log('Weekly panel missingness:', await page.locator('section[aria-labelledby="missingness-title"]').innerText())
  await page.screenshot({ path: info.outputPath('weekly-panel.png') })
})
