import { expect, test } from '@playwright/test'
import { showSqlSource, hideSqlSource } from './sql-pane'

test('editing preserves workflow identity and rejects a replacement from another source', async ({ page }) => {
  await page.goto('/app')
  const outcome = await page.evaluate(async () => {
    const { createWorkflowStore } = await import(new URL('/src/domain/workflowStore.ts', location.href).href)
    const { newImportRequestId, selectSource } = await import(new URL('/src/domain/workflow.ts', location.href).href)
    const { profileSourceInWorker } = await import(new URL('/src/data/client.ts', location.href).href)
    const { snapshotWorkflow, serialiseSnapshot } = await import(new URL('/src/domain/persistence.ts', location.href).href)
    const store = createWorkflowStore()
    const dispatch = store.getState().dispatch
    dispatch({ type: 'project-name-changed', value: 'Editor state' })
    dispatch({ type: 'project-submitted' })
    const file = new File(['value\n1\n2\n3\n'], 'values.csv', { type: 'text/csv' })
    dispatch({ type: 'file-selected', file })
    const request = newImportRequestId()
    dispatch({ type: 'profile-requested', request })
    const profile = await profileSourceInWorker(request, file)
    if (!profile.ok) throw new Error(JSON.stringify(profile.error))
    dispatch({ type: 'profile-succeeded', request, profile: profile.value })
    const original = store.getState()
    const before = serialiseSnapshot(snapshotWorkflow(original.workflow, '2026-09-17T00:00:00Z'))
    store.getState().openSourceEditor()
    const opened = store.getState().sourceEditor.kind === 'choosing' && store.getState().workflow === original.workflow
    store.getState().closeSourceEditor()
    const cancelled = store.getState().workflow === original.workflow && store.getState().preprocessing === original.preprocessing
    const saved = serialiseSnapshot(snapshotWorkflow(store.getState().workflow, '2026-09-17T00:00:00Z')) === before
    const replacement = selectSource(new File(['other\n4\n5\n'], 'other.csv', { type: 'text/csv' }))
    if (!replacement.ok) throw new Error('Invalid fixture')
    dispatch({ type: 'source-replaced', previous: replacement.value, source: replacement.value })
    const stale = store.getState().workflow === original.workflow
    store.getState().openSourceEditor()
    dispatch({ type: 'source-replaced', previous: original.workflow.source, source: replacement.value })
    const accepted = store.getState().workflow.kind === 'source-selected' && store.getState().sourceEditor.kind === 'closed' && store.getState().preprocessing === null
    dispatch({ type: 'project-closed' })
    dispatch({ type: 'source-replaced', previous: original.workflow.source, source: replacement.value })
    return { opened, cancelled, saved, stale, accepted, closed: store.getState().workflow.kind === 'awaiting-project' }
  })
  expect(outcome).toEqual({ opened: true, cancelled: true, saved: true, stale: true, accepted: true, closed: true })
})

test('direct upload can enter either editor without losing preparation on cancel', async ({ page }, info) => {
  test.setTimeout(120_000)
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Safe editing')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await page.locator('input[type=file]').setInputFiles({ name: 'measurements.csv', mimeType: 'text/csv', buffer: Buffer.from('value\n1\n2\n3\n') })
  await page.getByRole('button', { name: 'Inspect data', exact: true }).click()
  await page.getByRole('radio', { name: /^Independent observations/ }).check()
  await page.getByRole('checkbox', { name: 'value', exact: true }).check()
  await page.getByRole('button', { name: 'Create prepared dataset version', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Create prepared dataset version', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Edit data', exact: true }).scrollIntoViewIfNeeded()
  const profile = await page.locator('#data-profile-title').boundingBox()
  await page.getByRole('button', { name: 'Edit data', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Edit data', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Close edit data', exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toHaveCount(0)
  await expect(dialog.getByRole('button', { name: 'Cancel editing', exact: true })).toHaveCount(0)
  await expect(dialog).toHaveCSS('opacity', '1')
  expect(await page.locator('#data-profile-title').boundingBox()).toEqual(profile)
  const box = (await dialog.boundingBox())!
  expect(box.width).toBeLessThanOrEqual(470)
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.screenshot({ path: info.outputPath('edit-choice-modal.png') })
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: 'Edit data', exact: true }).click()
  await dialog.getByRole('button', { name: 'Close edit data' }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: 'Edit data', exact: true }).click()
  await expect(dialog).toBeVisible()
  await page.mouse.click(5, 5)
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('checkbox', { name: 'value', exact: true })).toBeChecked()
  for (const route of ['Build a pipeline', 'Prepare with SQL']) {
    await page.getByRole('button', { name: 'Edit data', exact: true }).click()
    await page.getByRole('button', { name: route, exact: true }).click()
    if (route === 'Prepare with SQL') {
      await expect(page.getByLabel('SQL console').locator('.xterm')).toBeVisible({ timeout: 30_000 })
      await showSqlSource(page)
    }
    else {
      await expect(page.getByTestId('block-input-measurements')).toContainText('3 rows, 1 column', { timeout: 30_000 })
      if (info.project.name === 'mobile-chromium') await page.getByRole('group', { name: 'Panes' }).getByRole('button', { name: 'Pipeline', exact: true }).click()
      const actions = page.getByRole('group', { name: 'Pipeline actions' })
      const [cancel, accept] = await actions.evaluate(element => Array.from(element.querySelectorAll('button')).map(button => { const rect = button.getBoundingClientRect(); return { y: rect.y, width: rect.width, height: rect.height } }))
      expect(Math.abs(cancel.y - accept.y)).toBeLessThan(1)
      expect(Math.abs(cancel.width - accept.width)).toBeLessThan(1)
      expect(Math.abs(cancel.height - accept.height)).toBeLessThan(1)
      const notice = (await page.getByTestId('pipeline-incomplete').boundingBox())!
      const instructions = (await page.getByText('Connect input files through transformation blocks', { exact: false }).boundingBox())!
      expect(notice.y).toBeGreaterThan(instructions.y + instructions.height)
      await expect(page.getByRole('banner').getByRole('button', { name: 'Cancel editing' })).toHaveCount(0)
    }
    await page.screenshot({ path: info.outputPath(`${route === 'Prepare with SQL' ? 'sql' : 'pipeline'}-editor.png`) })
    await page.getByRole('button', { name: 'Cancel editing', exact: true }).click()
    await expect(page.locator('#data-profile-title')).toHaveText('measurements.csv')
    await expect(page.getByRole('checkbox', { name: 'value', exact: true })).toBeChecked()
    await expect(page.getByRole('button', { name: 'Create prepared dataset version', exact: true })).toBeDisabled()
  }

  await page.getByRole('button', { name: 'Edit data', exact: true }).click()
  await page.getByRole('button', { name: 'Prepare with SQL', exact: true }).click()
  await showSqlSource(page)
  await expect(page.getByRole('button', { name: 'Refresh views' })).toBeEnabled({ timeout: 30_000 })
  await hideSqlSource(page)
  const terminal = page.getByLabel('SQL console').locator('.xterm-helper-textarea')
  await terminal.focus()
  await terminal.pressSequentially('CREATE OR REPLACE VIEW edited AS SELECT value * 2 AS doubled FROM measurements;')
  await terminal.press('Enter')
  await showSqlSource(page)
  await page.getByRole('button', { name: 'Refresh views' }).click()
  await expect(page.getByRole('button', { name: 'Use selected view' })).toBeEnabled({ timeout: 30_000 })
  await page.getByRole('button', { name: 'Use selected view' }).click()
  const confirm = page.getByRole('alertdialog', { name: 'Replace dataset?' })
  await expect(confirm).toBeVisible({ timeout: 30_000 })
  await confirm.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('SQL console').locator('.xterm')).toBeVisible()
  await showSqlSource(page)
  await page.getByRole('button', { name: 'Use selected view' }).click()
  await confirm.getByRole('button', { name: 'Replace dataset', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Source selected' })).toBeVisible()
  await page.getByRole('button', { name: 'Inspect data', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Physical schema' })).toContainText('doubled')
  await page.evaluate(async () => { const files = await import(new URL('/src/data/inputFiles.ts', location.href).href); files.forgetInputFiles() })
  await page.getByRole('button', { name: 'Edit data', exact: true }).click()
  await page.getByRole('button', { name: 'Edit SQL', exact: true }).click()
  await page.locator('input[type=file][multiple]').setInputFiles({ name: 'wrong.csv', mimeType: 'text/csv', buffer: Buffer.from('value\n9\n') })
  await expect(page.getByRole('alert')).toContainText('do not include measurements.csv')
  await page.locator('input[type=file][multiple]').setInputFiles({ name: 'measurements.csv', mimeType: 'text/csv', buffer: Buffer.from('value\n1\n2\n3\n') })
  await expect(page.getByLabel('SQL console').locator('.xterm')).toBeVisible({ timeout: 30_000 })
  await showSqlSource(page)
  await page.getByRole('button', { name: 'Cancel editing', exact: true }).click()
  await page.getByRole('button', { name: 'Edit data', exact: true }).click()
  await page.getByRole('button', { name: 'Edit SQL', exact: true }).click()
  await expect(page.getByLabel('SQL console').locator('.xterm')).toBeVisible({ timeout: 30_000 })
  await showSqlSource(page)
  await page.getByRole('button', { name: 'Cancel editing', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Physical schema' })).toContainText('doubled')
})
