import { expect, test } from '@playwright/test'

test('cancellable shell queries preserve direct-query Arrow values and schemas', async ({ page }) => {
  await page.goto('/app')
  const comparisons = await page.evaluate(async () => {
    const { queryParity } = await import(new URL(`/tests/fixtures/sql-session-harness.tsx?run=${Date.now()}`, location.href).href)
    return queryParity()
  })
  for (const result of comparisons) expect(result.pending, result.sql).toEqual(result.direct)
})

test('SQL batches return the final result and preserve DuckDB transaction and error behavior', async ({ page }) => {
  await page.goto('/app')
  const result = await page.evaluate(async () => {
    const { batchBehavior } = await import(new URL(`/tests/fixtures/sql-session-harness.tsx?run=${Date.now()}`, location.href).href)
    return batchBehavior()
  })
  expect(result).toEqual({ last: ['{"last": 2}'], rollback: ['{"n": 0}'], commit: ['{"n": 1}'], rejected: true, recovered: ['{"n": 1}'] })
})

test('SQL retains its terminal and cancels a batch after editor navigation', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/app')
  await page.evaluate(async () => {
    const { mount } = await import(new URL(`/tests/fixtures/sql-session-harness.tsx?run=${Date.now()}`, location.href).href)
    await mount()
  })
  const harness = page.locator('#sql-session-test')
  await expect(harness.getByRole('button', { name: 'Refresh views' })).toBeEnabled({ timeout: 30000 })
  const terminal = harness.getByLabel('SQL console').locator('.xterm')
  await terminal.evaluate(node => node.setAttribute('data-retained', 'yes'))
  const input = terminal.locator('.xterm-helper-textarea')
  await input.focus()
  await input.pressSequentially('CREATE VIEW first_view AS SELECT * FROM input; CREATE VIEW second_view AS SELECT x * 2 AS y FROM input;')
  await input.press('Enter')
  await harness.getByRole('button', { name: 'Refresh views' }).click()
  await expect(harness.getByRole('combobox', { name: 'Output view' })).toBeVisible()
  await harness.getByRole('combobox', { name: 'Output view' }).click()
  await page.getByRole('option', { name: 'second_view', exact: true }).click()
  await input.focus()
  await input.pressSequentially('SELECT 1; SELECT sum(sin(i::DOUBLE)) FROM range(1000000000) t(i); CREATE VIEW should_not_run AS SELECT 99;')
  await input.press('Enter')
  const identity = await harness.getByTestId('sql-session-state').textContent()
  await harness.getByRole('button', { name: 'Hide test editor' }).click()
  await expect(harness.getByLabel('SQL console')).toHaveCount(0)
  await expect(harness.getByTestId('sql-session-state')).toHaveText(identity!)
  await harness.getByRole('button', { name: 'Show test editor' }).click()
  await expect(terminal).toHaveAttribute('data-retained', 'yes')
  await expect(harness.getByRole('combobox', { name: 'Output view' })).toContainText('second_view')
  await expect(harness.getByTestId('sql-session-state')).toHaveText(identity!)
  await harness.getByRole('button', { name: 'Cancel query' }).click()
  await expect(harness.getByText('DuckDB accepted the cancellation request.', { exact: true })).toBeVisible({ timeout: 30000 })
  await harness.getByRole('button', { name: 'Refresh views' }).click()
  await harness.getByRole('combobox', { name: 'Output view' }).click()
  await expect(page.getByRole('option', { name: 'should_not_run', exact: true })).toHaveCount(0)
  await page.getByRole('option', { name: 'second_view', exact: true }).click()
  await harness.getByRole('button', { name: 'Use selected view' }).click()
  await expect(harness.getByRole('button', { name: 'Use selected view' })).toBeEnabled()
  await harness.getByRole('button', { name: 'Close test project' }).click()
  await harness.getByRole('button', { name: 'Inspect closed session' }).click()
  await expect(harness.getByTestId('closed-sql-session')).toHaveText('{"lifecycle":"closed","active":false}')
})
