import { expect, test } from '@playwright/test'
import { fileURLToPath } from 'node:url'
import { prepare } from './examples/support'

test('new survival regressions preserve covariates, validate settings, render and reopen', async ({ page }, info) => {
  test.setTimeout(180_000)
  const phone = info.project.name === 'mobile-chromium'
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  const name = `Survival regression checks ${info.project.name}`
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill(name)
  await page.getByRole('button', { name: 'Create project' }).click()
  await page.locator('input[type=file]').setInputFiles(fileURLToPath(new URL('../docs/2026-09-11-rviews-survival-veteran/data/veteran.csv', import.meta.url)))
  await page.getByRole('button', { name: /Inspect data/ }).click()
  await expect(page.getByText('Choose the observation structure')).toBeVisible({ timeout: 90_000 })
  await prepare(page, { structure: 'cross-section', columns: ['time', 'status', 'age', 'karno', 'prior', 'diagtime', 'trt'] })
  const chapter = async (pattern: RegExp) => {
    const toggle = page.getByRole('button', { name: 'Expand section list' })
    if (phone && await toggle.isVisible()) await toggle.click()
    await page.getByRole('navigation', { name: 'Workspace sections' }).getByRole('button', { name: pattern }).click()
  }
  await chapter(/Survival analysis/)
  const setup = page.locator('section[aria-labelledby="survival-setup-title"]')
  const choose = async (analysis: string) => setup.getByRole('radio', { name: analysis, exact: true }).click({ force: true })
  const run = () => setup.getByRole('button', { name: 'Run survival analysis' }).click()
  const checkEquation = async () => {
    const equation = page.getByTestId('survival-equation').first()
    await equation.locator('summary').first().click()
    await expect(equation.locator('.katex')).not.toHaveCount(0)
    await expect(equation.locator('.katex-error')).toHaveCount(0)
    const dimensions = await equation.evaluate((el) => ({
      width: el.clientWidth, content: el.scrollWidth,
      formulas: Array.from(el.querySelectorAll('.formula')).map((f) => ({ width: f.clientWidth, content: f.scrollWidth, text: f.getAttribute('aria-label') })),
    }))
    expect(dimensions.content, JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.width + 1)
    await equation.locator('summary').first().click()
  }
  const covariates = setup.getByRole('group', { name: 'Covariates', exact: true })
  await choose('Cox regression')
  await covariates.getByRole('checkbox', { name: 'age', exact: true }).check()
  await covariates.getByRole('checkbox', { name: 'karno', exact: true }).check()
  await choose('Aalen regression')
  await expect(covariates.getByRole('checkbox', { name: 'age', exact: true })).toBeChecked()
  await expect(covariates.getByRole('checkbox', { name: 'karno', exact: true })).toBeChecked()
  await run()
  await expect(page.getByRole(phone ? 'button' : 'heading', { name: 'Survival runs (1)', exact: true })).toBeVisible({ timeout: 60_000 })
  await expect(page.getByTestId('aalen-coefficients').first()).toBeVisible()
  await checkEquation()
  const plots = page.getByRole('region', { name: 'Cumulative coefficient plots' }).first()
  await expect(plots.getByTestId('aalen-coefficient-card')).toHaveCount(3)
  await plots.getByRole('searchbox', { name: 'Filter coefficients' }).fill('karno')
  await expect(plots.getByTestId('aalen-coefficient-card')).toHaveCount(1)
  await plots.getByRole('button', { name: 'Open karno cumulative coefficient in a floating window' }).click()
  await expect(page.getByRole('dialog', { name: 'karno cumulative coefficient' })).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export karno cumulative coefficient as SVG', exact: true }).click()
  expect((await download).suggestedFilename()).toMatch(/\.svg$/)
  await page.getByRole('button', { name: 'Close the floating window' }).click()
  await plots.getByRole('searchbox', { name: 'Filter coefficients' }).fill('')
  await choose('Survival forest')
  await expect(covariates.getByRole('checkbox', { name: 'age', exact: true })).toBeChecked()
  await setup.getByRole('spinbutton', { name: 'Candidate covariates per split', exact: true }).fill('3')
  await run()
  await expect(page.getByRole('alert')).toContainText('cannot exceed')
  await setup.getByRole('spinbutton', { name: 'Candidate covariates per split', exact: true }).fill('2')
  await setup.getByRole('spinbutton', { name: 'Prediction row', exact: true }).fill('138')
  await run()
  await expect(page.getByRole('alert')).toContainText('between 1 and 137')
  await setup.getByRole('spinbutton', { name: 'Prediction row', exact: true }).fill('1')
  await setup.getByRole('spinbutton', { name: 'Trees', exact: true }).fill('20')
  await covariates.getByRole('checkbox', { name: 'prior', exact: true }).check()
  await setup.getByRole('group', { name: 'Categorical covariates', exact: true }).getByRole('checkbox', { name: 'prior', exact: true }).check()
  await run()
  await expect(page.getByRole('alert')).toContainText('whole-number level codes from 1 to 53')
  await covariates.getByRole('checkbox', { name: 'prior', exact: true }).uncheck()
  await run()
  await expect(page.getByRole(phone ? 'button' : 'heading', { name: 'Survival runs (2)', exact: true })).toBeVisible({ timeout: 60_000 })
  await expect(page.getByTestId('survival-forest-survival').first()).toBeVisible()
  await expect(page.getByTestId('survival-forest-importance').first()).toBeVisible()
  await checkEquation()
  await expect(page.getByText('No confidence interval is calculated for this prediction.', { exact: false }).first()).toBeVisible()
  const fits = await page.locator('body').evaluate((el) => el.scrollWidth <= window.innerWidth + 1)
  expect(fits).toBe(true)
  await chapter(/Results/)
  await expect(page.getByRole('combobox', { name: 'Survival run' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Survival run' }).click()
  await page.getByRole('option', { name: /Aalen regression/ }).click()
  await expect(page.getByTestId('aalen-coefficients').first()).toBeVisible()
  await page.waitForTimeout(1000)
  await page.reload()
  await page.getByRole('button', { name: `Open ${name}`, exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Choose the data file again' })).toBeVisible()
  await page.locator('input[type=file]').setInputFiles(fileURLToPath(new URL('../docs/2026-09-11-rviews-survival-veteran/data/veteran.csv', import.meta.url)))
  await chapter(/Results/)
  await expect(page.getByRole('combobox', { name: 'Survival run' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Survival run' }).click()
  await page.getByRole('option', { name: /Survival forest/ }).click()
  await expect(page.getByTestId('survival-forest-survival').first()).toBeVisible()
  await checkEquation()
  await chapter(/Survival analysis/)
  await choose('Cox regression')
  for (const name of ['age', 'karno', 'prior', 'diagtime', 'trt']) {
    await covariates.getByRole('checkbox', { name, exact: true }).check()
  }
  await run()
  await expect(page.getByRole(phone ? 'button' : 'heading', { name: 'Survival runs (3)', exact: true })).toBeVisible({ timeout: 60_000 })
  const equation = page.getByTestId('survival-equation').first()
  await equation.locator('summary').first().click()
  await equation.evaluate((el) => { el.style.width = '320px' })
  const expression = equation.getByTestId('survival-equation-fitted').locator('.formula').first()
  await expect(expression.locator('.katex')).toHaveCount(1)
  const lines = await expression.locator('.katex-html > .base').evaluateAll((parts) => new Set(parts.map((part) => Math.round(part.getBoundingClientRect().top))).size)
  expect(lines).toBeGreaterThan(1)
  expect(await equation.evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await equation.screenshot({ path: info.outputPath('cox-wrapped-equation.png') })
  expect(errors).toEqual([])
})
