import { expect, test } from '@playwright/test'

test('temporal structure survives chapter navigation and keeps the fitted settings', async ({ page }) => {
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Temporal structure lifecycle')
  await page.getByRole('button', { name: 'Create project' }).click()
  const rows = Array.from({ length: 72 }, (_, i) => `${i},${Math.sin(i / 3) + i * 0.03},${Math.cos(i / 7)}`)
  await page.locator('input[type=file]').setInputFiles({ name: 'series.csv', mimeType: 'text/csv', buffer: Buffer.from(`time,x,y\n${rows.join('\n')}`) })
  await page.getByRole('button', { name: 'Inspect data' }).click()
  await page.getByRole('radio', { name: 'Regular time series' }).check()
  await page.getByRole('combobox', { name: 'Time column', exact: true }).click()
  await page.getByRole('option', { name: 'time', exact: true }).click()
  await page.getByRole('checkbox', { name: 'x', exact: true }).check()
  await page.getByRole('checkbox', { name: 'y', exact: true }).check()
  await page.getByRole('button', { name: 'Create prepared dataset version' }).click()
  await page.getByRole('radio', { name: /Breaks/ }).check()
  await page.getByRole('spinbutton', { name: 'Min segment' }).fill('7')
  await page.getByRole('button', { name: 'Analyse temporal structure' }).click()
  await expect(page.getByTestId('acf-pacf')).toHaveCount(2, { timeout: 30_000 })
  const chapters = page.getByRole('navigation', { name: 'Workspace chapters' })
  await chapters.getByRole('button', { name: /DAG workspace/ }).click()
  await chapters.getByRole('button', { name: /Data studio/ }).click()
  await expect(page.getByRole('radio', { name: 'Regular time series' })).toBeChecked()
  await expect(page.getByRole('button', { name: 'Create prepared dataset version' })).toHaveCount(0)
  await page.getByRole('radio', { name: /Breaks/ }).check()
  await expect(page.getByTestId('acf-pacf')).toHaveCount(2)
  await expect(page.getByText('min segment 7', { exact: true })).toBeVisible()
  await page.getByRole('radio', { name: /Redundancy/ }).check()
  await page.getByRole('button', { name: 'Analyse redundancy' }).click()
  await expect(page.getByTestId('correlation-matrix')).toBeVisible()
  await chapters.getByRole('button', { name: /DAG workspace/ }).click()
  await chapters.getByRole('button', { name: /Data studio/ }).click()
  await page.getByRole('radio', { name: /Redundancy/ }).check()
  await expect(page.getByTestId('correlation-matrix')).toBeVisible()
  await expect(page.getByTestId('pairwise-scatter')).toBeVisible()
})
