import { expect, test } from '@playwright/test'
import { chapter } from './examples/support'

test('temporal structure survives chapter navigation and keeps the fitted settings', async ({ page }) => {
  await page.goto('/app')
  await page.getByRole('textbox', { name: 'Project name' }).fill('Temporal structure lifecycle')
  await page.getByRole('button', { name: 'Create project' }).click()
  const rows = Array.from({ length: 72 }, (_, i) => `${i},${Math.sin(i / 3) + i * 0.03},${Math.cos(i / 7)}`)
  await page.locator('input[type=file]').setInputFiles({ name: 'series.csv', mimeType: 'text/csv', buffer: Buffer.from(`time,x,y\n${rows.join('\n')}`) })
  await page.getByRole('button', { name: 'Inspect data' }).click()
  await page.getByRole('radio', { name: 'Regular time series' }).check()
  await page.getByRole('combobox', { name: 'Time column', exact: true }).click()
  await page.getByRole('option', { name: 'time', exact: true }).click()
  await page.getByRole('checkbox', { name: 'x', exact: true }).check()
  await page.getByRole('checkbox', { name: 'y', exact: true }).check()
  await page.getByRole('button', { name: 'Create prepared dataset version' }).click()
  await page.getByRole('radio', { name: /Breaks/ }).check()
  await page.getByRole('spinbutton', { name: 'Min segment' }).fill('7')
  await page.getByRole('button', { name: 'Analyse temporal structure' }).click()
  await expect(page.getByTestId('acf-pacf')).toHaveCount(2, { timeout: 30_000 })
  await chapter(page, /DAG workspace/)
  await chapter(page, /Data studio/)
  await expect(page.getByRole('radio', { name: 'Regular time series' })).toBeChecked()
  await expect(page.getByRole('button', { name: 'Create prepared dataset version' })).toHaveCount(0)
  await expect(page.getByRole('radio', { name: /Breaks/ })).toBeChecked()
  await page.getByRole('radio', { name: /Breaks/ }).check()
  await expect(page.getByRole('spinbutton', { name: 'Min segment' })).toHaveValue('7')
  await expect(page.getByTestId('acf-pacf')).toHaveCount(2)
  await expect(page.getByText('min segment 7', { exact: true })).toBeVisible()
  await page.getByRole('radio', { name: /Redundancy/ }).check()
  await page.getByRole('spinbutton', { name: '|r| threshold', exact: true }).fill('0.8')
  await page.getByRole('spinbutton', { name: 'VIF threshold', exact: true }).fill('8')
  await page.getByRole('button', { name: 'Analyse redundancy' }).click()
  await expect(page.getByTestId('correlation-matrix')).toBeVisible()
  await chapter(page, /DAG workspace/)
  await chapter(page, /Data studio/)
  await expect(page.getByRole('radio', { name: /Redundancy/ })).toBeChecked()
  await expect(page.getByRole('spinbutton', { name: '|r| threshold', exact: true })).toHaveValue('0.8')
  await expect(page.getByRole('spinbutton', { name: 'VIF threshold', exact: true })).toHaveValue('8')
  await page.getByRole('radio', { name: /Redundancy/ }).check()
  await expect(page.getByTestId('correlation-matrix')).toBeVisible()
  await expect(page.getByTestId('pairwise-scatter')).toBeVisible()
  await page.getByRole('radio', { name: /Stationarity/ }).check()
  const selection = page.getByRole('group', { name: 'Stationarity variables', exact: true })
  await selection.getByRole('checkbox', { name: 'x', exact: true }).check()
  await chapter(page, /DAG workspace/)
  await chapter(page, /Data studio/)
  await expect(page.getByRole('radio', { name: /Stationarity/ })).toBeChecked()
  await expect(selection.getByRole('checkbox', { name: 'x', exact: true })).toBeChecked()
  await expect(selection.getByRole('checkbox', { name: 'y', exact: true })).not.toBeChecked()
  await page.getByRole('radio', { name: /Granger/ }).check()
  await page.getByRole('combobox', { name: 'Candidate cause', exact: true }).click()
  await page.getByRole('option', { name: 'x', exact: true }).click()
  await page.getByRole('combobox', { name: 'Target', exact: true }).click()
  await page.getByRole('option', { name: 'y', exact: true }).click()
  await chapter(page, /DAG workspace/)
  await chapter(page, /Data studio/)
  await expect(page.getByRole('radio', { name: /Granger/ })).toBeChecked()
  await expect(page.getByRole('combobox', { name: 'Candidate cause', exact: true })).toContainText('x')
  await expect(page.getByRole('combobox', { name: 'Target', exact: true })).toContainText('y')
})
