import { RunActions } from '@/components/ui/RunActions'
import {useState,type ReactNode} from 'react'
import {useWorkflow} from '@/components/WorkflowProvider'
import {useTimeSeriesDraft} from './useTimeSeriesDraft'
import {useJob} from '@/analysis/JobsProvider'
import {useRunActivity} from '@/lib/useRunActivity'
import {JobNotice} from '@/components/ui/JobNotice'
import {Alert} from '@/components/ui/Alert'
import {Select} from '@/components/ui/Select'
import {SegmentedControl} from '@/components/ui/SegmentedControl'
import {ColumnChecklist} from '@/components/ui/ColumnChecklist'
import {SettingsStep} from '@/components/ui/SettingsStep'
import {WorkbenchLayout} from '@/components/shell/WorkbenchLayout'
import {Icon} from '@/components/Icon'
import {button,chapterIntroSingle,field,fieldLabel,fieldHint,fieldRow,panel,stepsStack,iconControl} from '@/components/ui/recipes'
import {isNumericDuckDbType,type ColumnId} from '@/domain/dataset'
import type {PreparedDatasetArtifact} from '@/domain/preprocessing'
import {initialPanelRegression,type PanelRegressionDraft} from '@/domain/panelRegression'
import {isRegressionDesignRun,newTimeSeriesRunId,parseTimeSeriesRun} from '@/domain/timeSeries'
import {describeAnalysisWorkerProblem} from '@/workers/analysisProtocol'
import type {TimeSeriesPanelProps} from './TimeSeriesPanel'
import {ChapterHeading} from '@/components/ui/ChapterHeading'
import {TimeSeriesHistory} from './TimeSeriesHistory'
import {TimeSeriesRunResult} from './TimeSeriesRunResult'

export type PanelRegressionPanelProps = Pick<TimeSeriesPanelProps,'source'|'profile'|'runs'|'onRun'|'onDeleteRun'|'onActivity'> & {readonly prepared:PreparedDatasetArtifact;readonly selector?:ReactNode;readonly analysisSelector?:ReactNode;readonly inspectorLead?:ReactNode;readonly runLabel?:string;readonly onRestore?:(controls:PanelRegressionDraft)=>void}

export function PanelRegressionPanel(props:PanelRegressionPanelProps){
  const draft=useTimeSeriesDraft(props.prepared.id,s=>s.panelRegression),change=useWorkflow(s=>s.changeTimeSeries)
  const set=(value:PanelRegressionDraft)=>change(props.prepared.id,{type:'panel-regression',value})
  const session=useJob('estimation:regression-designs'),busy=session.job.kind==='running'
  useRunActivity(props.onActivity,busy?{label:'Panel regression',progress:null}:null)
  const [term,setTerm]=useState<readonly (ColumnId|null)[]>([null,null,null])
  const columns=props.profile.columns.filter(c=>props.prepared.columns.includes(c.id)&&isNumericDuckDbType(c.duckdbType))
  const model=draft.model,isPanel=props.prepared.kind==='prepared-panel'
  const runs=props.runs.filter(isRegressionDesignRun).filter(run=>run.kind==='panel-regression'||run.kind==='bacon')
  const choose=(label:string,value:ColumnId|null,onChange:(v:ColumnId|null)=>void,empty='Choose a column')=><label><span className={fieldLabel}>{label}</span><Select aria-label={label} className={field('text','mt-1')} value={value??''} onChange={e=>onChange(columns.find(c=>c.id===e.target.value)?.id??null)}><option value="">{empty}</option>{columns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></label>
  const input=(label:string,value:string,onChange:(v:string)=>void)=><label><span className={fieldLabel}>{label}</span><input aria-label={label} className={field('text','mt-1')} value={value} onChange={e=>onChange(e.target.value)}/></label>
  const problem=draft.outcome===null?'Choose an outcome.':model.kind!=='interactions'&&!isPanel?'Prepare panel data to use adoption timing.':model.kind!=='interactions'&&model.onset===null?'Choose an absorbing treatment indicator.':model.kind==='interactions'&&(model.predictors.length===0||model.terms.length===0)?'Select predictors and model terms.':model.kind!=='bacon'&&draft.cluster===null&&!isPanel?'Choose a cluster column.':null
  const execute=async()=>{
    if(problem!==null)return
    const current=session.start('analysis','Preparing regression design');if(current===null)return
    try{
      const {preparePanelRegression}=await import('@/data/panelRegressionInput')
      const prepared=await preparePanelRegression(props.source,props.profile,props.prepared,draft,()=>session.current(current))
      if(!session.current(current))return
      if(!prepared.ok){session.fail(current,prepared.error);return}
      const data=prepared.value,{runPanelRegression,runBacon}=await import('@/analysis/client')
      const result=data.kind==='bacon'?await runBacon(data.values,data.request):await runPanelRegression(data.values,data.request)
      if(!session.current(current))return
      if(!result.ok){session.fail(current,describeAnalysisWorkerProblem(result.error));return}
      const saved=parseTimeSeriesRun({kind:data.kind==='bacon'?'bacon':'panel-regression',id:newTimeSeriesRunId(),createdAt:new Date().toISOString(),preparedDataset:props.prepared.id,controls:draft,outcome:data.variables[data.request.outcome],variables:data.variables,specification:data.request,evidence:result.value,...(data.kind==='bacon'?{periods:data.periods}:{})})
      if(!saved.ok){session.fail(current,saved.error);return}
      props.onRun(saved.value);session.finish(current)
    }catch(e:unknown){session.fail(current,e instanceof Error?e.message:String(e))}
  }
  return <WorkbenchLayout id="panel-regression" bottom={{trigger:{label:'History',icon:'history'},title:'Regression and decomposition runs',defaultSize:150,body:<TimeSeriesHistory label="Regression-design runs" entries={props.runs.filter(isRegressionDesignRun)} onDelete={r=>props.onDeleteRun(r.id)}/>}} inspector={{trigger:{label:'Requirements',icon:'contract'},title:'Model requirements',body:<div className="flex flex-col gap-4">{props.inspectorLead}<div className="space-y-3 text-body text-muted"><p>{model.kind==='interactions'?'Choose numeric or categorical coding for each predictor. Categorical coding requires an observed reference value. Main effects and lower-order interactions accompany each interaction.':'This route requires a balanced panel with regular periods. Adoption must be absorbing: 0 before adoption and 1 thereafter.'}</p><p>{model.kind==='bacon'?'Observation weights are not supported by this decomposition. Covariate-adjusted and unadjusted decompositions have different components.':'Clusters are treated as independent. Observation weights must be non-negative for CR2 regression and strictly positive for the event-study fit.'}</p><p>Neither a fitted regression nor its decomposition establishes the identifying assumptions needed for a causal interpretation.</p></div></div>}} stage={<section className="@container/panel flex flex-col gap-5"><div><ChapterHeading className="mb-2">Estimation</ChapterHeading><p className={chapterIntroSingle}>Fit regression event studies and interaction models, or decompose a two-way fixed-effects coefficient. A causal interpretation requires a justified study design and its identifying assumptions.</p></div><section className={panel('p-(--panel-space)')}>{props.selector}<fieldset disabled={busy} className="m-0 mt-6 min-w-0 border-0 p-0"><legend className="sr-only">Panel regression specification</legend><div className={stepsStack}>
    <SettingsStep number={1} title="Choose the analysis">{props.analysisSelector??<SegmentedControl className="justify-self-start" ariaLabel="Regression analysis" value={model.kind} options={[{value:'eventStudy',label:'Regression event study',disabled:!isPanel},{value:'interactions',label:'Interactions / DDD'},{value:'bacon',label:'Bacon decomposition',disabled:!isPanel}]} onChange={kind=>{const initial=initialPanelRegression();set({...draft,model:kind==='interactions'?{kind,predictors:[],terms:[]}:kind==='bacon'?{kind,onset:null,covariates:[]}:initial.model});setTerm([null,null,null])}}/>}</SettingsStep>
    <SettingsStep number={2} title="Choose columns and inference"><div className={fieldRow.two}>{choose('Outcome',draft.outcome,outcome=>set({...draft,outcome}))}{model.kind==='bacon'?choose('Treatment indicator',model.onset,onset=>set({...draft,model:{...model,onset}})):choose('Cluster column',draft.cluster,cluster=>set({...draft,cluster}),isPanel?'Panel unit':'Choose a column')}</div>{model.kind!=='bacon'&&<div className={fieldRow.two}>{choose('Observation weights',draft.weight,weight=>set({...draft,weight}),'Equal weights')}{input('Confidence level',draft.confidence,confidence=>set({...draft,confidence}))}</div>}
    {model.kind!=='interactions'&&<>{model.kind==='eventStudy'&&<div className={fieldRow.two}>{choose('Treatment indicator',model.onset,onset=>set({...draft,model:{...model,onset}}))}</div>}<p className={fieldHint}>Use 0 before adoption and 1 from adoption onward. Never-treated units remain 0.</p><ColumnChecklist title="Covariates" help="Additional numeric regressors." columns={columns} selected={model.covariates} reserved={[draft.outcome,model.onset,draft.weight,draft.cluster].filter((c):c is ColumnId=>c!==null)} onChange={covariates=>set({...draft,model:{...model,covariates}})}/></>}
    {model.kind==='interactions'&&<><ColumnChecklist title="Predictors" help="Select main effects and variables used in interactions. Fixed effects can be represented by categorical predictors." columns={columns} selected={model.predictors.map(p=>p.column)} reserved={[draft.outcome,draft.weight].filter((c):c is ColumnId=>c!==null)} onChange={ids=>set({...draft,model:{...model,predictors:ids.map(column=>model.predictors.find(p=>p.column===column)??{column,coding:{kind:'numeric'}}),terms:[...model.terms.filter(t=>t.every(id=>ids.includes(id))),...ids.filter(id=>!model.predictors.some(p=>p.column===id)).map(id=>[id])]}})}/>{model.predictors.map(p=><div key={p.column} className={fieldRow.two}><label><span className={fieldLabel}>{columns.find(c=>c.id===p.column)?.name} coding</span><Select aria-label={`${columns.find(c=>c.id===p.column)?.name} coding`} className={field('text','mt-1')} value={p.coding.kind} onChange={e=>set({...draft,model:{...model,predictors:model.predictors.map(v=>v.column!==p.column?v:{...p,coding:e.target.value==='categorical'?{kind:'categorical',reference:'0'}:{kind:'numeric'}})}})}><option value="numeric">Numeric</option><option value="categorical">Categorical</option></Select></label>{p.coding.kind==='categorical'&&input(`${columns.find(c=>c.id===p.column)?.name} reference`,p.coding.reference,reference=>set({...draft,model:{...model,predictors:model.predictors.map(v=>v.column!==p.column?v:{...p,coding:{kind:'categorical',reference}})}}))}</div>)}</>}
    </SettingsStep>
    {model.kind==='eventStudy'&&<SettingsStep number={3} title="Define the event window"><div className={fieldRow.three}>{input('First event period',model.first,first=>set({...draft,model:{...model,first}}))}{input('Last event period',model.last,last=>set({...draft,model:{...model,last}}))}{input('Reference event period',model.reference,reference=>set({...draft,model:{...model,reference}}))}</div><SegmentedControl ariaLabel="Event window tails" value={model.tails} options={[{value:'reference',label:'Outside rows share reference'},{value:'bin',label:'Bin endpoint periods'}]} onChange={tails=>set({...draft,model:{...model,tails}})}/></SettingsStep>}
    {model.kind==='interactions'&&<SettingsStep number={3} title="Specify interactions"><p className={fieldHint}>Choose two predictors for a pair interaction or three for a triple interaction. All lower-order terms are included.</p><div className={fieldRow.three}>{term.map((v,i)=><label key={i}><span className={fieldLabel}>Interaction factor {i+1}</span><Select aria-label={`Interaction factor ${i+1}`} className={field('text','mt-1')} value={v??''} onChange={e=>setTerm(term.map((t,j)=>j===i?model.predictors.find(p=>p.column===e.target.value)?.column??null:t))}><option value="">{i===2?'None (pair)':'Choose predictor'}</option>{model.predictors.map(p=><option key={p.column} value={p.column}>{columns.find(c=>c.id===p.column)?.name}</option>)}</Select></label>)}</div><button type="button" className={button('quiet')} disabled={term[0]===null||term[1]===null||new Set(term.filter(t=>t!==null)).size!==term.filter(t=>t!==null).length} onClick={()=>{const added=term.filter((t):t is ColumnId=>t!==null);if(!model.terms.some(t=>t.length===added.length&&t.every(c=>added.includes(c))))set({...draft,model:{...model,terms:[...model.terms,added]}})}}>Add interaction</button><ul className="m-0 list-none space-y-2 p-0">{model.terms.filter(t=>t.length>1).map((t,i)=><li key={i} className="flex items-center justify-between gap-3 text-body"><span>{t.map(id=>columns.find(c=>c.id===id)?.name).join(' × ')}</span><button className={iconControl('quiet')} aria-label={`Remove interaction ${i+1}`} onClick={()=>set({...draft,model:{...model,terms:model.terms.filter(v=>v!==t)}})}><Icon name="delete" size={16}/></button></li>)}</ul></SettingsStep>}
    </div></fieldset><div className="mt-6 space-y-3">{problem!==null&&<Alert tone="info" live={false}>{problem}</Alert>}<RunActions running={busy} onCancel={session.cancel} orbLabel={model.kind==='bacon'?'Decomposition running':'Panel regression running'}><button className={button('signal')} disabled={busy||session.blocked||problem!==null} aria-busy={busy} onClick={()=>void execute()}>{props.runLabel??(model.kind==='bacon'?'Decompose coefficient':model.kind==='eventStudy'?'Fit event study':'Fit interaction regression')}</button></RunActions><JobNotice job={session.job}/></div></section>{runs.slice(-1).map(run=><div key={run.id} className="space-y-3"><button className={button('quiet')} disabled={busy} onClick={()=>{set(run.controls);props.onRestore?.(run.controls)}}>Restore this specification</button><TimeSeriesRunResult run={run}/></div>)}</section>}/>
}
