[workspace]

[package]
name = "hirmos-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hirmos-causal-core = { path = "../causal-core" }
js-sys = "0.3"
nalgebra = "0.34"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
wasm-bindgen = "0.2"

[profile.release]
lto = "thin"
opt-level = "s"
